// Generated from the SVGO reference tables (plugins/_collections.js) -- do not edit by hand.
@file:Suppress("ktlint")

package io.github.tobsef.svgo

/** Deprecated attribute sets of an element or attribute group. */
public class DeprecatedAttrs(
    public val safe: Set<String> = emptySet(),
    public val unsafe: Set<String> = emptySet(),
)

/** Allowed attributes/content description of a single SVG element. */
public class ElemConfig(
    public val attrsGroups: Set<String> = emptySet(),
    public val attrs: Set<String>? = null,
    public val defaults: Map<String, String>? = null,
    public val deprecated: DeprecatedAttrs? = null,
    public val contentGroups: Set<String>? = null,
    public val content: Set<String>? = null,
)

public val attrsGroups: Map<String, Set<String>> = mapOf(
    "animationAddition" to setOf(
        "additive",
        "accumulate",
    ),
    "animationAttributeTarget" to setOf(
        "attributeType",
        "attributeName",
    ),
    "animationEvent" to setOf(
        "onbegin",
        "onend",
        "onrepeat",
        "onload",
    ),
    "animationTiming" to setOf(
        "begin",
        "dur",
        "end",
        "fill",
        "max",
        "min",
        "repeatCount",
        "repeatDur",
        "restart",
    ),
    "animationValue" to setOf(
        "by",
        "calcMode",
        "from",
        "keySplines",
        "keyTimes",
        "to",
        "values",
    ),
    "conditionalProcessing" to setOf(
        "requiredExtensions",
        "requiredFeatures",
        "systemLanguage",
    ),
    "core" to setOf(
        "id",
        "tabindex",
        "xml:base",
        "xml:lang",
        "xml:space",
    ),
    "graphicalEvent" to setOf(
        "onactivate",
        "onclick",
        "onfocusin",
        "onfocusout",
        "onload",
        "onmousedown",
        "onmousemove",
        "onmouseout",
        "onmouseover",
        "onmouseup",
    ),
    "presentation" to setOf(
        "alignment-baseline",
        "baseline-shift",
        "clip-path",
        "clip-rule",
        "clip",
        "color-interpolation-filters",
        "color-interpolation",
        "color-profile",
        "color-rendering",
        "color",
        "cursor",
        "direction",
        "display",
        "dominant-baseline",
        "enable-background",
        "fill-opacity",
        "fill-rule",
        "fill",
        "filter",
        "flood-color",
        "flood-opacity",
        "font-family",
        "font-size-adjust",
        "font-size",
        "font-stretch",
        "font-style",
        "font-variant",
        "font-weight",
        "glyph-orientation-horizontal",
        "glyph-orientation-vertical",
        "image-rendering",
        "letter-spacing",
        "lighting-color",
        "marker-end",
        "marker-mid",
        "marker-start",
        "mask",
        "opacity",
        "overflow",
        "paint-order",
        "pointer-events",
        "shape-rendering",
        "stop-color",
        "stop-opacity",
        "stroke-dasharray",
        "stroke-dashoffset",
        "stroke-linecap",
        "stroke-linejoin",
        "stroke-miterlimit",
        "stroke-opacity",
        "stroke-width",
        "stroke",
        "text-anchor",
        "text-decoration",
        "text-overflow",
        "text-rendering",
        "transform-origin",
        "transform",
        "unicode-bidi",
        "vector-effect",
        "visibility",
        "word-spacing",
        "writing-mode",
    ),
    "xlink" to setOf(
        "xlink:actuate",
        "xlink:arcrole",
        "xlink:href",
        "xlink:role",
        "xlink:show",
        "xlink:title",
        "xlink:type",
    ),
    "documentEvent" to setOf(
        "onabort",
        "onerror",
        "onresize",
        "onscroll",
        "onunload",
        "onzoom",
    ),
    "documentElementEvent" to setOf(
        "oncopy",
        "oncut",
        "onpaste",
    ),
    "globalEvent" to setOf(
        "oncancel",
        "oncanplay",
        "oncanplaythrough",
        "onchange",
        "onclick",
        "onclose",
        "oncuechange",
        "ondblclick",
        "ondrag",
        "ondragend",
        "ondragenter",
        "ondragleave",
        "ondragover",
        "ondragstart",
        "ondrop",
        "ondurationchange",
        "onemptied",
        "onended",
        "onerror",
        "onfocus",
        "oninput",
        "oninvalid",
        "onkeydown",
        "onkeypress",
        "onkeyup",
        "onload",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onmousedown",
        "onmouseenter",
        "onmouseleave",
        "onmousemove",
        "onmouseout",
        "onmouseover",
        "onmouseup",
        "onmousewheel",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onreset",
        "onresize",
        "onscroll",
        "onseeked",
        "onseeking",
        "onselect",
        "onshow",
        "onstalled",
        "onsubmit",
        "onsuspend",
        "ontimeupdate",
        "ontoggle",
        "onvolumechange",
        "onwaiting",
    ),
    "filterPrimitive" to setOf(
        "x",
        "y",
        "width",
        "height",
        "result",
    ),
    "transferFunction" to setOf(
        "amplitude",
        "exponent",
        "intercept",
        "offset",
        "slope",
        "tableValues",
        "type",
    ),
)

public val attrsGroupsDefaults: Map<String, Map<String, String>> = mapOf(
    "core" to mapOf(
        "xml:space" to "default",
    ),
    "presentation" to mapOf(
        "clip" to "auto",
        "clip-path" to "none",
        "clip-rule" to "nonzero",
        "mask" to "none",
        "opacity" to "1",
        "stop-color" to "#000",
        "stop-opacity" to "1",
        "fill-opacity" to "1",
        "fill-rule" to "nonzero",
        "fill" to "#000",
        "stroke" to "none",
        "stroke-width" to "1",
        "stroke-linecap" to "butt",
        "stroke-linejoin" to "miter",
        "stroke-miterlimit" to "4",
        "stroke-dasharray" to "none",
        "stroke-dashoffset" to "0",
        "stroke-opacity" to "1",
        "paint-order" to "normal",
        "vector-effect" to "none",
        "display" to "inline",
        "visibility" to "visible",
        "marker-start" to "none",
        "marker-mid" to "none",
        "marker-end" to "none",
        "color-interpolation" to "sRGB",
        "color-interpolation-filters" to "linearRGB",
        "color-rendering" to "auto",
        "shape-rendering" to "auto",
        "text-rendering" to "auto",
        "image-rendering" to "auto",
        "font-style" to "normal",
        "font-variant" to "normal",
        "font-weight" to "normal",
        "font-stretch" to "normal",
        "font-size" to "medium",
        "font-size-adjust" to "none",
        "kerning" to "auto",
        "letter-spacing" to "normal",
        "word-spacing" to "normal",
        "text-decoration" to "none",
        "text-anchor" to "start",
        "text-overflow" to "clip",
        "writing-mode" to "lr-tb",
        "glyph-orientation-vertical" to "auto",
        "glyph-orientation-horizontal" to "0deg",
        "direction" to "ltr",
        "unicode-bidi" to "normal",
        "dominant-baseline" to "auto",
        "alignment-baseline" to "baseline",
        "baseline-shift" to "baseline",
    ),
    "transferFunction" to mapOf(
        "slope" to "1",
        "intercept" to "0",
        "amplitude" to "1",
        "exponent" to "1",
        "offset" to "0",
    ),
)

public val attrsGroupsDeprecated: Map<String, DeprecatedAttrs> = mapOf(
    "animationAttributeTarget" to DeprecatedAttrs(unsafe = setOf(
            "attributeType",
        )),
    "conditionalProcessing" to DeprecatedAttrs(unsafe = setOf(
            "requiredFeatures",
        )),
    "core" to DeprecatedAttrs(unsafe = setOf(
            "xml:base",
            "xml:lang",
            "xml:space",
        )),
    "presentation" to DeprecatedAttrs(unsafe = setOf(
            "clip",
            "color-profile",
            "enable-background",
            "glyph-orientation-horizontal",
            "glyph-orientation-vertical",
            "kerning",
        )),
)

public val colorsNames: Map<String, String> = mapOf(
    "aliceblue" to "#f0f8ff",
    "antiquewhite" to "#faebd7",
    "aqua" to "#0ff",
    "aquamarine" to "#7fffd4",
    "azure" to "#f0ffff",
    "beige" to "#f5f5dc",
    "bisque" to "#ffe4c4",
    "black" to "#000",
    "blanchedalmond" to "#ffebcd",
    "blue" to "#00f",
    "blueviolet" to "#8a2be2",
    "brown" to "#a52a2a",
    "burlywood" to "#deb887",
    "cadetblue" to "#5f9ea0",
    "chartreuse" to "#7fff00",
    "chocolate" to "#d2691e",
    "coral" to "#ff7f50",
    "cornflowerblue" to "#6495ed",
    "cornsilk" to "#fff8dc",
    "crimson" to "#dc143c",
    "cyan" to "#0ff",
    "darkblue" to "#00008b",
    "darkcyan" to "#008b8b",
    "darkgoldenrod" to "#b8860b",
    "darkgray" to "#a9a9a9",
    "darkgreen" to "#006400",
    "darkgrey" to "#a9a9a9",
    "darkkhaki" to "#bdb76b",
    "darkmagenta" to "#8b008b",
    "darkolivegreen" to "#556b2f",
    "darkorange" to "#ff8c00",
    "darkorchid" to "#9932cc",
    "darkred" to "#8b0000",
    "darksalmon" to "#e9967a",
    "darkseagreen" to "#8fbc8f",
    "darkslateblue" to "#483d8b",
    "darkslategray" to "#2f4f4f",
    "darkslategrey" to "#2f4f4f",
    "darkturquoise" to "#00ced1",
    "darkviolet" to "#9400d3",
    "deeppink" to "#ff1493",
    "deepskyblue" to "#00bfff",
    "dimgray" to "#696969",
    "dimgrey" to "#696969",
    "dodgerblue" to "#1e90ff",
    "firebrick" to "#b22222",
    "floralwhite" to "#fffaf0",
    "forestgreen" to "#228b22",
    "fuchsia" to "#f0f",
    "gainsboro" to "#dcdcdc",
    "ghostwhite" to "#f8f8ff",
    "gold" to "#ffd700",
    "goldenrod" to "#daa520",
    "gray" to "#808080",
    "green" to "#008000",
    "greenyellow" to "#adff2f",
    "grey" to "#808080",
    "honeydew" to "#f0fff0",
    "hotpink" to "#ff69b4",
    "indianred" to "#cd5c5c",
    "indigo" to "#4b0082",
    "ivory" to "#fffff0",
    "khaki" to "#f0e68c",
    "lavender" to "#e6e6fa",
    "lavenderblush" to "#fff0f5",
    "lawngreen" to "#7cfc00",
    "lemonchiffon" to "#fffacd",
    "lightblue" to "#add8e6",
    "lightcoral" to "#f08080",
    "lightcyan" to "#e0ffff",
    "lightgoldenrodyellow" to "#fafad2",
    "lightgray" to "#d3d3d3",
    "lightgreen" to "#90ee90",
    "lightgrey" to "#d3d3d3",
    "lightpink" to "#ffb6c1",
    "lightsalmon" to "#ffa07a",
    "lightseagreen" to "#20b2aa",
    "lightskyblue" to "#87cefa",
    "lightslategray" to "#789",
    "lightslategrey" to "#789",
    "lightsteelblue" to "#b0c4de",
    "lightyellow" to "#ffffe0",
    "lime" to "#0f0",
    "limegreen" to "#32cd32",
    "linen" to "#faf0e6",
    "magenta" to "#f0f",
    "maroon" to "#800000",
    "mediumaquamarine" to "#66cdaa",
    "mediumblue" to "#0000cd",
    "mediumorchid" to "#ba55d3",
    "mediumpurple" to "#9370db",
    "mediumseagreen" to "#3cb371",
    "mediumslateblue" to "#7b68ee",
    "mediumspringgreen" to "#00fa9a",
    "mediumturquoise" to "#48d1cc",
    "mediumvioletred" to "#c71585",
    "midnightblue" to "#191970",
    "mintcream" to "#f5fffa",
    "mistyrose" to "#ffe4e1",
    "moccasin" to "#ffe4b5",
    "navajowhite" to "#ffdead",
    "navy" to "#000080",
    "oldlace" to "#fdf5e6",
    "olive" to "#808000",
    "olivedrab" to "#6b8e23",
    "orange" to "#ffa500",
    "orangered" to "#ff4500",
    "orchid" to "#da70d6",
    "palegoldenrod" to "#eee8aa",
    "palegreen" to "#98fb98",
    "paleturquoise" to "#afeeee",
    "palevioletred" to "#db7093",
    "papayawhip" to "#ffefd5",
    "peachpuff" to "#ffdab9",
    "peru" to "#cd853f",
    "pink" to "#ffc0cb",
    "plum" to "#dda0dd",
    "powderblue" to "#b0e0e6",
    "purple" to "#800080",
    "rebeccapurple" to "#639",
    "red" to "#f00",
    "rosybrown" to "#bc8f8f",
    "royalblue" to "#4169e1",
    "saddlebrown" to "#8b4513",
    "salmon" to "#fa8072",
    "sandybrown" to "#f4a460",
    "seagreen" to "#2e8b57",
    "seashell" to "#fff5ee",
    "sienna" to "#a0522d",
    "silver" to "#c0c0c0",
    "skyblue" to "#87ceeb",
    "slateblue" to "#6a5acd",
    "slategray" to "#708090",
    "slategrey" to "#708090",
    "snow" to "#fffafa",
    "springgreen" to "#00ff7f",
    "steelblue" to "#4682b4",
    "tan" to "#d2b48c",
    "teal" to "#008080",
    "thistle" to "#d8bfd8",
    "tomato" to "#ff6347",
    "turquoise" to "#40e0d0",
    "violet" to "#ee82ee",
    "wheat" to "#f5deb3",
    "white" to "#fff",
    "whitesmoke" to "#f5f5f5",
    "yellow" to "#ff0",
    "yellowgreen" to "#9acd32",
)

public val colorsProps: Set<String> = setOf(
    "color",
    "fill",
    "flood-color",
    "lighting-color",
    "stop-color",
    "stroke",
)

public val colorsShortNames: Map<String, String> = mapOf(
    "#f0ffff" to "azure",
    "#f5f5dc" to "beige",
    "#ffe4c4" to "bisque",
    "#a52a2a" to "brown",
    "#ff7f50" to "coral",
    "#ffd700" to "gold",
    "#808080" to "gray",
    "#008000" to "green",
    "#4b0082" to "indigo",
    "#fffff0" to "ivory",
    "#f0e68c" to "khaki",
    "#faf0e6" to "linen",
    "#800000" to "maroon",
    "#000080" to "navy",
    "#808000" to "olive",
    "#ffa500" to "orange",
    "#da70d6" to "orchid",
    "#cd853f" to "peru",
    "#ffc0cb" to "pink",
    "#dda0dd" to "plum",
    "#800080" to "purple",
    "#f00" to "red",
    "#ff0000" to "red",
    "#fa8072" to "salmon",
    "#a0522d" to "sienna",
    "#c0c0c0" to "silver",
    "#fffafa" to "snow",
    "#d2b48c" to "tan",
    "#008080" to "teal",
    "#ff6347" to "tomato",
    "#ee82ee" to "violet",
    "#f5deb3" to "wheat",
)

public val editorNamespaces: Set<String> = setOf(
    "http://creativecommons.org/ns#",
    "http://inkscape.sourceforge.net/DTD/sodipodi-0.dtd",
    "http://krita.org/namespaces/svg/krita",
    "http://ns.adobe.com/AdobeIllustrator/10.0/",
    "http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/",
    "http://ns.adobe.com/Extensibility/1.0/",
    "http://ns.adobe.com/Flows/1.0/",
    "http://ns.adobe.com/GenericCustomNamespace/1.0/",
    "http://ns.adobe.com/Graphs/1.0/",
    "http://ns.adobe.com/ImageReplacement/1.0/",
    "http://ns.adobe.com/SaveForWeb/1.0/",
    "http://ns.adobe.com/Variables/1.0/",
    "http://ns.adobe.com/XPath/1.0/",
    "http://purl.org/dc/elements/1.1/",
    "http://schemas.microsoft.com/visio/2003/SVGExtensions/",
    "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
    "http://taptrix.com/vectorillustrator/svg_extensions",
    "http://www.bohemiancoding.com/sketch/ns",
    "http://www.figma.com/figma/ns",
    "http://www.inkscape.org/namespaces/inkscape",
    "http://www.serif.com/",
    "http://www.vector.evaxdesign.sk",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "https://boxy-svg.com",
)

private fun elemsChunk0(): List<Pair<String, ElemConfig>> = listOf(
    "a" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "style",
            "target",
            "transform",
        ),
        defaults = mapOf(
            "target" to "_self",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
            "tspan",
        ),
    ),
    "altGlyph" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "dx",
            "dy",
            "externalResourcesRequired",
            "format",
            "glyphRef",
            "rotate",
            "style",
            "x",
            "y",
        ),
    ),
    "altGlyphDef" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        content = setOf(
            "glyphRef",
        ),
    ),
    "altGlyphItem" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        content = setOf(
            "glyphRef",
            "altGlyphItem",
        ),
    ),
    "animate" to ElemConfig(
        attrsGroups = setOf(
            "animationAddition",
            "animationAttributeTarget",
            "animationEvent",
            "animationTiming",
            "animationValue",
            "conditionalProcessing",
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "animateColor" to ElemConfig(
        attrsGroups = setOf(
            "animationAddition",
            "animationAttributeTarget",
            "animationEvent",
            "animationTiming",
            "animationValue",
            "conditionalProcessing",
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "animateMotion" to ElemConfig(
        attrsGroups = setOf(
            "animationAddition",
            "animationEvent",
            "animationTiming",
            "animationValue",
            "conditionalProcessing",
            "core",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "keyPoints",
            "origin",
            "path",
            "rotate",
        ),
        defaults = mapOf(
            "rotate" to "0",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "mpath",
        ),
    ),
    "animateTransform" to ElemConfig(
        attrsGroups = setOf(
            "animationAddition",
            "animationAttributeTarget",
            "animationEvent",
            "animationTiming",
            "animationValue",
            "conditionalProcessing",
            "core",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "type",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
)

private fun elemsChunk1(): List<Pair<String, ElemConfig>> = listOf(
    "circle" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "cx",
            "cy",
            "externalResourcesRequired",
            "r",
            "style",
            "transform",
        ),
        defaults = mapOf(
            "cx" to "0",
            "cy" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "clipPath" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "clipPathUnits",
            "externalResourcesRequired",
            "style",
            "transform",
        ),
        defaults = mapOf(
            "clipPathUnits" to "userSpaceOnUse",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "shape",
        ),
        content = setOf(
            "text",
            "use",
        ),
    ),
    "color-profile" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "xlink",
        ),
        attrs = setOf(
            "local",
            "name",
            "rendering-intent",
        ),
        defaults = mapOf(
            "name" to "sRGB",
            "rendering-intent" to "auto",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "name",
            )),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "cursor" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "conditionalProcessing",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "x",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "defs" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "desc" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
    ),
    "ellipse" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "cx",
            "cy",
            "externalResourcesRequired",
            "rx",
            "ry",
            "style",
            "transform",
        ),
        defaults = mapOf(
            "cx" to "0",
            "cy" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "feBlend" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
            "in2",
            "mode",
        ),
        defaults = mapOf(
            "mode" to "normal",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
)

private fun elemsChunk2(): List<Pair<String, ElemConfig>> = listOf(
    "feColorMatrix" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
            "type",
            "values",
        ),
        defaults = mapOf(
            "type" to "matrix",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feComponentTransfer" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
        ),
        content = setOf(
            "feFuncA",
            "feFuncB",
            "feFuncG",
            "feFuncR",
        ),
    ),
    "feComposite" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "in",
            "in2",
            "k1",
            "k2",
            "k3",
            "k4",
            "operator",
            "style",
        ),
        defaults = mapOf(
            "operator" to "over",
            "k1" to "0",
            "k2" to "0",
            "k3" to "0",
            "k4" to "0",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feConvolveMatrix" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "in",
            "kernelMatrix",
            "order",
            "style",
            "bias",
            "divisor",
            "edgeMode",
            "targetX",
            "targetY",
            "kernelUnitLength",
            "preserveAlpha",
        ),
        defaults = mapOf(
            "order" to "3",
            "bias" to "0",
            "edgeMode" to "duplicate",
            "preserveAlpha" to "false",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feDiffuseLighting" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "diffuseConstant",
            "in",
            "kernelUnitLength",
            "style",
            "surfaceScale",
        ),
        defaults = mapOf(
            "surfaceScale" to "1",
            "diffuseConstant" to "1",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "feDistantLight",
            "fePointLight",
            "feSpotLight",
        ),
    ),
    "feDisplacementMap" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "in",
            "in2",
            "scale",
            "style",
            "xChannelSelector",
            "yChannelSelector",
        ),
        defaults = mapOf(
            "scale" to "0",
            "xChannelSelector" to "A",
            "yChannelSelector" to "A",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feDistantLight" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "azimuth",
            "elevation",
        ),
        defaults = mapOf(
            "azimuth" to "0",
            "elevation" to "0",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feFlood" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
        content = setOf(
            "animate",
            "animateColor",
            "set",
        ),
    ),
)

private fun elemsChunk3(): List<Pair<String, ElemConfig>> = listOf(
    "feFuncA" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "transferFunction",
        ),
        content = setOf(
            "set",
            "animate",
        ),
    ),
    "feFuncB" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "transferFunction",
        ),
        content = setOf(
            "set",
            "animate",
        ),
    ),
    "feFuncG" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "transferFunction",
        ),
        content = setOf(
            "set",
            "animate",
        ),
    ),
    "feFuncR" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "transferFunction",
        ),
        content = setOf(
            "set",
            "animate",
        ),
    ),
    "feGaussianBlur" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
            "stdDeviation",
        ),
        defaults = mapOf(
            "stdDeviation" to "0",
        ),
        content = setOf(
            "set",
            "animate",
        ),
    ),
    "feImage" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "href",
            "preserveAspectRatio",
            "style",
            "xlink:href",
        ),
        defaults = mapOf(
            "preserveAspectRatio" to "xMidYMid meet",
        ),
        content = setOf(
            "animate",
            "animateTransform",
            "set",
        ),
    ),
    "feMerge" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
        content = setOf(
            "feMergeNode",
        ),
    ),
    "feMergeNode" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "in",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
)

private fun elemsChunk4(): List<Pair<String, ElemConfig>> = listOf(
    "feMorphology" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
            "operator",
            "radius",
        ),
        defaults = mapOf(
            "operator" to "erode",
            "radius" to "0",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feOffset" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
            "dx",
            "dy",
        ),
        defaults = mapOf(
            "dx" to "0",
            "dy" to "0",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "fePointLight" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "x",
            "y",
            "z",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
            "z" to "0",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feSpecularLighting" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "in",
            "kernelUnitLength",
            "specularConstant",
            "specularExponent",
            "style",
            "surfaceScale",
        ),
        defaults = mapOf(
            "surfaceScale" to "1",
            "specularConstant" to "1",
            "specularExponent" to "1",
        ),
        contentGroups = setOf(
            "descriptive",
            "lightSource",
        ),
    ),
    "feSpotLight" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "limitingConeAngle",
            "pointsAtX",
            "pointsAtY",
            "pointsAtZ",
            "specularExponent",
            "x",
            "y",
            "z",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
            "z" to "0",
            "pointsAtX" to "0",
            "pointsAtY" to "0",
            "pointsAtZ" to "0",
            "specularExponent" to "1",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feTile" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "class",
            "style",
            "in",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "feTurbulence" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "filterPrimitive",
        ),
        attrs = setOf(
            "baseFrequency",
            "class",
            "numOctaves",
            "seed",
            "stitchTiles",
            "style",
            "type",
        ),
        defaults = mapOf(
            "baseFrequency" to "0",
            "numOctaves" to "1",
            "seed" to "0",
            "stitchTiles" to "noStitch",
            "type" to "turbulence",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
    "filter" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "filterRes",
            "filterUnits",
            "height",
            "href",
            "primitiveUnits",
            "style",
            "width",
            "x",
            "xlink:href",
            "y",
        ),
        defaults = mapOf(
            "primitiveUnits" to "userSpaceOnUse",
            "x" to "-10%",
            "y" to "-10%",
            "width" to "120%",
            "height" to "120%",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "filterRes",
            )),
        contentGroups = setOf(
            "descriptive",
            "filterPrimitive",
        ),
        content = setOf(
            "animate",
            "set",
        ),
    ),
)

private fun elemsChunk5(): List<Pair<String, ElemConfig>> = listOf(
    "font" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "horiz-adv-x",
            "horiz-origin-x",
            "horiz-origin-y",
            "style",
            "vert-adv-y",
            "vert-origin-x",
            "vert-origin-y",
        ),
        defaults = mapOf(
            "horiz-origin-x" to "0",
            "horiz-origin-y" to "0",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "horiz-origin-x",
                "horiz-origin-y",
                "vert-adv-y",
                "vert-origin-x",
                "vert-origin-y",
            )),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "font-face",
            "glyph",
            "hkern",
            "missing-glyph",
            "vkern",
        ),
    ),
    "font-face" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "font-family",
            "font-style",
            "font-variant",
            "font-weight",
            "font-stretch",
            "font-size",
            "unicode-range",
            "units-per-em",
            "panose-1",
            "stemv",
            "stemh",
            "slope",
            "cap-height",
            "x-height",
            "accent-height",
            "ascent",
            "descent",
            "widths",
            "bbox",
            "ideographic",
            "alphabetic",
            "mathematical",
            "hanging",
            "v-ideographic",
            "v-alphabetic",
            "v-mathematical",
            "v-hanging",
            "underline-position",
            "underline-thickness",
            "strikethrough-position",
            "strikethrough-thickness",
            "overline-position",
            "overline-thickness",
        ),
        defaults = mapOf(
            "font-style" to "all",
            "font-variant" to "normal",
            "font-weight" to "all",
            "font-stretch" to "normal",
            "unicode-range" to "U+0-10FFFF",
            "units-per-em" to "1000",
            "panose-1" to "0 0 0 0 0 0 0 0 0 0",
            "slope" to "0",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "accent-height",
                "alphabetic",
                "ascent",
                "bbox",
                "cap-height",
                "descent",
                "hanging",
                "ideographic",
                "mathematical",
                "panose-1",
                "slope",
                "stemh",
                "stemv",
                "unicode-range",
                "units-per-em",
                "v-alphabetic",
                "v-hanging",
                "v-ideographic",
                "v-mathematical",
                "widths",
                "x-height",
            )),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "font-face-src",
        ),
    ),
    "font-face-format" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "string",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "string",
            )),
    ),
    "font-face-name" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "name",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "name",
            )),
    ),
    "font-face-src" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        content = setOf(
            "font-face-name",
            "font-face-uri",
        ),
    ),
    "font-face-uri" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "xlink",
        ),
        attrs = setOf(
            "href",
            "xlink:href",
        ),
        content = setOf(
            "font-face-format",
        ),
    ),
    "foreignObject" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "style",
            "transform",
            "width",
            "x",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
        ),
    ),
    "g" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
)

private fun elemsChunk6(): List<Pair<String, ElemConfig>> = listOf(
    "glyph" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "arabic-form",
            "class",
            "d",
            "glyph-name",
            "horiz-adv-x",
            "lang",
            "orientation",
            "style",
            "unicode",
            "vert-adv-y",
            "vert-origin-x",
            "vert-origin-y",
        ),
        defaults = mapOf(
            "arabic-form" to "initial",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "arabic-form",
                "glyph-name",
                "horiz-adv-x",
                "orientation",
                "unicode",
                "vert-adv-y",
                "vert-origin-x",
                "vert-origin-y",
            )),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "glyphRef" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "d",
            "horiz-adv-x",
            "style",
            "vert-adv-y",
            "vert-origin-x",
            "vert-origin-y",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "horiz-adv-x",
                "vert-adv-y",
                "vert-origin-x",
                "vert-origin-y",
            )),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "hatch" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "hatchContentUnits",
            "hatchUnits",
            "pitch",
            "rotate",
            "style",
            "transform",
            "x",
            "y",
        ),
        defaults = mapOf(
            "hatchUnits" to "objectBoundingBox",
            "hatchContentUnits" to "userSpaceOnUse",
            "x" to "0",
            "y" to "0",
            "pitch" to "0",
            "rotate" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
        content = setOf(
            "hatchPath",
        ),
    ),
    "hatchPath" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "style",
            "d",
            "offset",
        ),
        defaults = mapOf(
            "offset" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "hkern" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "u1",
            "g1",
            "u2",
            "g2",
            "k",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "g1",
                "g2",
                "k",
                "u1",
                "u2",
            )),
    ),
    "image" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "href",
            "preserveAspectRatio",
            "style",
            "transform",
            "width",
            "x",
            "xlink:href",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
            "preserveAspectRatio" to "xMidYMid meet",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "line" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "style",
            "transform",
            "x1",
            "x2",
            "y1",
            "y2",
        ),
        defaults = mapOf(
            "x1" to "0",
            "y1" to "0",
            "x2" to "0",
            "y2" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "linearGradient" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "gradientTransform",
            "gradientUnits",
            "href",
            "spreadMethod",
            "style",
            "x1",
            "x2",
            "xlink:href",
            "y1",
            "y2",
        ),
        defaults = mapOf(
            "x1" to "0",
            "y1" to "0",
            "x2" to "100%",
            "y2" to "0",
            "spreadMethod" to "pad",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "animate",
            "animateTransform",
            "set",
            "stop",
        ),
    ),
)

private fun elemsChunk7(): List<Pair<String, ElemConfig>> = listOf(
    "marker" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "markerHeight",
            "markerUnits",
            "markerWidth",
            "orient",
            "preserveAspectRatio",
            "refX",
            "refY",
            "style",
            "viewBox",
        ),
        defaults = mapOf(
            "markerUnits" to "strokeWidth",
            "refX" to "0",
            "refY" to "0",
            "markerWidth" to "3",
            "markerHeight" to "3",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "mask" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "mask-type",
            "maskContentUnits",
            "maskUnits",
            "style",
            "width",
            "x",
            "y",
        ),
        defaults = mapOf(
            "maskUnits" to "objectBoundingBox",
            "maskContentUnits" to "userSpaceOnUse",
            "x" to "-10%",
            "y" to "-10%",
            "width" to "120%",
            "height" to "120%",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "metadata" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
    ),
    "missing-glyph" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "d",
            "horiz-adv-x",
            "style",
            "vert-adv-y",
            "vert-origin-x",
            "vert-origin-y",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "horiz-adv-x",
                "vert-adv-y",
                "vert-origin-x",
                "vert-origin-y",
            )),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "mpath" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "href",
            "xlink:href",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "path" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "d",
            "externalResourcesRequired",
            "pathLength",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "pattern" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "href",
            "patternContentUnits",
            "patternTransform",
            "patternUnits",
            "preserveAspectRatio",
            "style",
            "viewBox",
            "width",
            "x",
            "xlink:href",
            "y",
        ),
        defaults = mapOf(
            "patternUnits" to "objectBoundingBox",
            "patternContentUnits" to "userSpaceOnUse",
            "x" to "0",
            "y" to "0",
            "width" to "0",
            "height" to "0",
            "preserveAspectRatio" to "xMidYMid meet",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "polygon" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "points",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
)

private fun elemsChunk8(): List<Pair<String, ElemConfig>> = listOf(
    "polyline" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "points",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "radialGradient" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "cx",
            "cy",
            "externalResourcesRequired",
            "fr",
            "fx",
            "fy",
            "gradientTransform",
            "gradientUnits",
            "href",
            "r",
            "spreadMethod",
            "style",
            "xlink:href",
        ),
        defaults = mapOf(
            "gradientUnits" to "objectBoundingBox",
            "cx" to "50%",
            "cy" to "50%",
            "r" to "50%",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "animate",
            "animateTransform",
            "set",
            "stop",
        ),
    ),
    "meshGradient" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "style",
            "x",
            "y",
            "gradientUnits",
            "transform",
        ),
        contentGroups = setOf(
            "descriptive",
            "paintServer",
            "animation",
        ),
        content = setOf(
            "meshRow",
        ),
    ),
    "meshRow" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "meshPatch",
        ),
    ),
    "meshPatch" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "stop",
        ),
    ),
    "rect" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "rx",
            "ry",
            "style",
            "transform",
            "width",
            "x",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "script" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "type",
            "href",
            "xlink:href",
        ),
    ),
    "set" to ElemConfig(
        attrsGroups = setOf(
            "animation",
            "animationAttributeTarget",
            "animationTiming",
            "conditionalProcessing",
            "core",
            "xlink",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "to",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
)

private fun elemsChunk9(): List<Pair<String, ElemConfig>> = listOf(
    "solidColor" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
        contentGroups = setOf(
            "paintServer",
        ),
    ),
    "stop" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "style",
            "offset",
            "path",
        ),
        content = setOf(
            "animate",
            "animateColor",
            "set",
        ),
    ),
    "style" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "type",
            "media",
            "title",
        ),
        defaults = mapOf(
            "type" to "text/css",
        ),
    ),
    "svg" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "documentEvent",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "baseProfile",
            "class",
            "contentScriptType",
            "contentStyleType",
            "height",
            "preserveAspectRatio",
            "style",
            "version",
            "viewBox",
            "width",
            "x",
            "y",
            "zoomAndPan",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
            "width" to "100%",
            "height" to "100%",
            "preserveAspectRatio" to "xMidYMid meet",
            "zoomAndPan" to "magnify",
            "version" to "1.1",
            "baseProfile" to "none",
            "contentScriptType" to "application/ecmascript",
            "contentStyleType" to "text/css",
        ),
        deprecated = DeprecatedAttrs(safe = setOf(
                "version",
            ), unsafe = setOf(
                "baseProfile",
                "contentScriptType",
                "contentStyleType",
                "zoomAndPan",
            )),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "switch" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "style",
            "transform",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "shape",
        ),
        content = setOf(
            "a",
            "foreignObject",
            "g",
            "image",
            "svg",
            "switch",
            "text",
            "use",
        ),
    ),
    "symbol" to ElemConfig(
        attrsGroups = setOf(
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "preserveAspectRatio",
            "refX",
            "refY",
            "style",
            "viewBox",
        ),
        defaults = mapOf(
            "refX" to "0",
            "refY" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "paintServer",
            "shape",
            "structural",
        ),
        content = setOf(
            "a",
            "altGlyphDef",
            "clipPath",
            "color-profile",
            "cursor",
            "filter",
            "font-face",
            "font",
            "foreignObject",
            "image",
            "marker",
            "mask",
            "pattern",
            "script",
            "style",
            "switch",
            "text",
            "view",
        ),
    ),
    "text" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "dx",
            "dy",
            "externalResourcesRequired",
            "lengthAdjust",
            "rotate",
            "style",
            "textLength",
            "transform",
            "x",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
            "lengthAdjust" to "spacing",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
            "textContentChild",
        ),
        content = setOf(
            "a",
        ),
    ),
    "textPath" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "d",
            "externalResourcesRequired",
            "href",
            "method",
            "spacing",
            "startOffset",
            "style",
            "xlink:href",
        ),
        defaults = mapOf(
            "startOffset" to "0",
            "method" to "align",
            "spacing" to "exact",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "a",
            "altGlyph",
            "animate",
            "animateColor",
            "set",
            "tref",
            "tspan",
        ),
    ),
)

private fun elemsChunk10(): List<Pair<String, ElemConfig>> = listOf(
    "title" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "class",
            "style",
        ),
    ),
    "tref" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "href",
            "style",
            "xlink:href",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "animate",
            "animateColor",
            "set",
        ),
    ),
    "tspan" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
        ),
        attrs = setOf(
            "class",
            "dx",
            "dy",
            "externalResourcesRequired",
            "lengthAdjust",
            "rotate",
            "style",
            "textLength",
            "x",
            "y",
        ),
        contentGroups = setOf(
            "descriptive",
        ),
        content = setOf(
            "a",
            "altGlyph",
            "animate",
            "animateColor",
            "set",
            "tref",
            "tspan",
        ),
    ),
    "use" to ElemConfig(
        attrsGroups = setOf(
            "conditionalProcessing",
            "core",
            "graphicalEvent",
            "presentation",
            "xlink",
        ),
        attrs = setOf(
            "class",
            "externalResourcesRequired",
            "height",
            "href",
            "style",
            "transform",
            "width",
            "x",
            "xlink:href",
            "y",
        ),
        defaults = mapOf(
            "x" to "0",
            "y" to "0",
        ),
        contentGroups = setOf(
            "animation",
            "descriptive",
        ),
    ),
    "view" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "externalResourcesRequired",
            "preserveAspectRatio",
            "viewBox",
            "viewTarget",
            "zoomAndPan",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "viewTarget",
                "zoomAndPan",
            )),
        contentGroups = setOf(
            "descriptive",
        ),
    ),
    "vkern" to ElemConfig(
        attrsGroups = setOf(
            "core",
        ),
        attrs = setOf(
            "u1",
            "g1",
            "u2",
            "g2",
            "k",
        ),
        deprecated = DeprecatedAttrs(unsafe = setOf(
                "g1",
                "g2",
                "k",
                "u1",
                "u2",
            )),
    ),
)

public val elems: Map<String, ElemConfig> = buildMap {
    putAll(elemsChunk0())
    putAll(elemsChunk1())
    putAll(elemsChunk2())
    putAll(elemsChunk3())
    putAll(elemsChunk4())
    putAll(elemsChunk5())
    putAll(elemsChunk6())
    putAll(elemsChunk7())
    putAll(elemsChunk8())
    putAll(elemsChunk9())
    putAll(elemsChunk10())
}

public val elemsGroups: Map<String, Set<String>> = mapOf(
    "animation" to setOf(
        "animate",
        "animateColor",
        "animateMotion",
        "animateTransform",
        "set",
    ),
    "descriptive" to setOf(
        "desc",
        "metadata",
        "title",
    ),
    "shape" to setOf(
        "circle",
        "ellipse",
        "line",
        "path",
        "polygon",
        "polyline",
        "rect",
    ),
    "structural" to setOf(
        "defs",
        "g",
        "svg",
        "symbol",
        "use",
    ),
    "paintServer" to setOf(
        "hatch",
        "linearGradient",
        "meshGradient",
        "pattern",
        "radialGradient",
        "solidColor",
    ),
    "nonRendering" to setOf(
        "clipPath",
        "filter",
        "linearGradient",
        "marker",
        "mask",
        "pattern",
        "radialGradient",
        "solidColor",
        "symbol",
    ),
    "container" to setOf(
        "a",
        "defs",
        "foreignObject",
        "g",
        "marker",
        "mask",
        "missing-glyph",
        "pattern",
        "svg",
        "switch",
        "symbol",
    ),
    "textContent" to setOf(
        "a",
        "altGlyph",
        "altGlyphDef",
        "altGlyphItem",
        "glyph",
        "glyphRef",
        "text",
        "textPath",
        "tref",
        "tspan",
    ),
    "textContentChild" to setOf(
        "altGlyph",
        "textPath",
        "tref",
        "tspan",
    ),
    "lightSource" to setOf(
        "feDiffuseLighting",
        "feDistantLight",
        "fePointLight",
        "feSpecularLighting",
        "feSpotLight",
    ),
    "filterPrimitive" to setOf(
        "feBlend",
        "feColorMatrix",
        "feComponentTransfer",
        "feComposite",
        "feConvolveMatrix",
        "feDiffuseLighting",
        "feDisplacementMap",
        "feDropShadow",
        "feFlood",
        "feFuncA",
        "feFuncB",
        "feFuncG",
        "feFuncR",
        "feGaussianBlur",
        "feImage",
        "feMerge",
        "feMergeNode",
        "feMorphology",
        "feOffset",
        "feSpecularLighting",
        "feTile",
        "feTurbulence",
    ),
)

public val inheritableAttrs: Set<String> = setOf(
    "clip-rule",
    "color-interpolation-filters",
    "color-interpolation",
    "color-profile",
    "color-rendering",
    "color",
    "cursor",
    "direction",
    "dominant-baseline",
    "fill-opacity",
    "fill-rule",
    "fill",
    "font-family",
    "font-size-adjust",
    "font-size",
    "font-stretch",
    "font-style",
    "font-variant",
    "font-weight",
    "font",
    "glyph-orientation-horizontal",
    "glyph-orientation-vertical",
    "image-rendering",
    "letter-spacing",
    "marker-end",
    "marker-mid",
    "marker-start",
    "marker",
    "paint-order",
    "pointer-events",
    "shape-rendering",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-opacity",
    "stroke-width",
    "stroke",
    "text-anchor",
    "text-rendering",
    "transform",
    "visibility",
    "word-spacing",
    "writing-mode",
)

public val pathElems: Set<String> = setOf(
    "glyph",
    "missing-glyph",
    "path",
)

public val presentationNonInheritableGroupAttrs: Set<String> = setOf(
    "clip-path",
    "display",
    "filter",
    "mask",
    "opacity",
    "text-decoration",
    "transform",
    "unicode-bidi",
)

public val pseudoClasses: Map<String, Set<String>> = mapOf(
    "displayState" to setOf(
        "fullscreen",
        "modal",
        "picture-in-picture",
    ),
    "input" to setOf(
        "autofill",
        "blank",
        "checked",
        "default",
        "disabled",
        "enabled",
        "in-range",
        "indeterminate",
        "invalid",
        "optional",
        "out-of-range",
        "placeholder-shown",
        "read-only",
        "read-write",
        "required",
        "user-invalid",
        "valid",
    ),
    "linguistic" to setOf(
        "dir",
        "lang",
    ),
    "location" to setOf(
        "any-link",
        "link",
        "local-link",
        "scope",
        "target-within",
        "target",
        "visited",
    ),
    "resourceState" to setOf(
        "playing",
        "paused",
    ),
    "timeDimensional" to setOf(
        "current",
        "past",
        "future",
    ),
    "treeStructural" to setOf(
        "empty",
        "first-child",
        "first-of-type",
        "last-child",
        "last-of-type",
        "nth-child",
        "nth-last-child",
        "nth-last-of-type",
        "nth-of-type",
        "only-child",
        "only-of-type",
        "root",
    ),
    "userAction" to setOf(
        "active",
        "focus-visible",
        "focus-within",
        "focus",
        "hover",
    ),
    "functional" to setOf(
        "is",
        "not",
        "where",
        "has",
    ),
)

public val referencesProps: Set<String> = setOf(
    "clip-path",
    "color-profile",
    "fill",
    "filter",
    "marker-end",
    "marker-mid",
    "marker-start",
    "mask",
    "stroke",
    "style",
)

public val textElems: Set<String> = setOf(
    "a",
    "altGlyph",
    "altGlyphDef",
    "altGlyphItem",
    "glyph",
    "glyphRef",
    "text",
    "textPath",
    "tref",
    "tspan",
    "pre",
    "title",
)
