export const cases = [
  // --- shorthand merging (restructShorthand)
  ".a{padding-top:1em;padding-right:1em;padding-bottom:1em;padding-left:1em}",
  ".a{margin-top:1px;margin-right:2px;margin-bottom:3px;margin-left:4px}",
  ".a{margin-top:1px;margin-right:2px;margin-bottom:1px;margin-left:2px}",
  ".a{margin-top:1px;margin-right:2px;margin-bottom:3px;margin-left:2px}",
  ".a{margin-top:0;margin-right:0;margin-bottom:0;margin-left:0}",
  ".a{padding-top:1em;padding-right:1em;padding-bottom:1em}",
  ".a{margin:1px;margin-top:2px}",
  ".a{margin-top:2px;margin:1px}",
  ".a{margin:1px 2px;margin-left:3px}",
  ".a{margin-top:1px!important;margin-right:1px!important;margin-bottom:1px!important;margin-left:1px!important}",
  ".a{margin-top:1px!important;margin-right:1px;margin-bottom:1px;margin-left:1px}",
  ".a{margin-top:1rem;margin-right:1rem;margin-bottom:1rem;margin-left:1rem}",
  ".a{margin-top:1vw;margin-right:1vw;margin-bottom:1vw;margin-left:1vw}",
  ".a{margin-top:var(--x);margin-right:var(--x);margin-bottom:var(--x);margin-left:var(--x)}",
  ".a{margin-top:inherit;margin-right:inherit;margin-bottom:inherit;margin-left:inherit}",
  ".a{margin-top:inherit;margin-right:1px;margin-bottom:1px;margin-left:1px}",
  ".a{border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px}",
  ".a{border-top-color:red;border-right-color:red;border-bottom-color:red;border-left-color:red}",
  ".a{border-top-style:solid;border-right-style:solid;border-bottom-style:solid;border-left-style:solid}",
  ".a{padding-top:1px;padding-right:1px;padding-bottom:1px;padding-left:1px;margin-top:2px;margin-right:2px;margin-bottom:2px;margin-left:2px}",
  ".a{padding-top:1px}.a{padding-right:1px}.a{padding-bottom:1px}.a{padding-left:1px}",
  ".a{padding-top:1px}.b{color:red}.a{padding-right:1px;padding-bottom:1px;padding-left:1px}",
  ".a{margin-top:calc(1px + 2px);margin-right:calc(1px + 2px);margin-bottom:calc(1px + 2px);margin-left:calc(1px + 2px)}",
  ".a{margin-top:1px\\9;margin-right:1px;margin-bottom:1px;margin-left:1px}",
  // --- duplicate / needless declarations (restructBlock)
  ".a{color:red;color:blue}",
  ".a{color:red!important;color:blue}",
  ".a{color:red;color:blue!important}",
  ".a{margin:1px;margin-top:2px;margin:3px}",
  ".a{font:12px serif;font-size:14px}",
  ".a{font-size:14px;font:12px serif}",
  ".a{list-style-type:disc;list-style:none}",
  ".a{border:1px solid red;border-top-width:2px}",
  ".a{border-top-width:2px;border:1px solid red}",
  ".a{display:block;display:table}",
  ".a{display:block;display:inline}",
  ".a{position:absolute;position:fixed}",
  ".a{text-align:left;text-align:justify-all}",
  ".a{background:url(a.png);background:url(b.png)}",
  ".a{src:url(a.woff);src:url(b.woff)}",
  ".a{cursor:pointer;cursor:zoom-in}",
  ".a{overflow:hidden;overflow:clip}",
  ".a{color:red;-webkit-color:blue;color:green}",
  // --- rule merging (initialMergeRuleset / mergeRuleset / restructRuleset)
  ".a{color:red}.a{background:blue}",
  ".a{color:red}.b{color:red}",
  ".a{color:red}b{color:red}",
  ".a,.b{color:red}.c{color:red}",
  ".a{color:red}.b{color:green}.c{color:red}",
  ".a{color:red;background:blue}.b{color:red;background:blue}",
  ".a{color:red;background:blue;border:0}.b{color:red;background:blue}",
  ".a{color:red;background:blue}.b{color:red;background:blue;border:0}",
  ".a{color:red;background:blue;font-size:10px}.b{color:red;background:blue;padding:2px}",
  "a{color:red}a{color:red}",
  ".a{color:red}div{color:blue}.a{background:green}",
  "p{color:red}p span{color:red}",
  ".a:hover{color:red}.b:hover{color:red}",
  ".a::after{color:red}.b::after{color:red}",
  ".a:focus{color:red}.b{color:red}",
  ".a{color:red}.b{color:red}.c{color:red}.d{color:red}",
  "#i{color:red}.c{color:red}tag{color:red}",
  // --- at-rules
  "@media screen{.a{color:red}}@media screen{.b{color:blue}}",
  "@media screen and (max-width: 200px){.a{display:none}}",
  ".a{color:red}@media print{.a{color:blue}}.b{color:red}",
  "@keyframes a{from{opacity:0}to{opacity:1}}.x{color:red}@keyframes a{from{opacity:.5}}",
  "@supports (display:grid){.a{display:grid}.b{display:grid}}",
  "@font-face{font-family:x;src:url(a.woff);src:url(b.woff)}",
  "@import url(a.css);.a{color:red}",
  "@charset \"utf-8\";.a{color:red}",
  "@media screen{}",
  ".a{}",
  "/*! keep */.a{color:red}/* drop */",
  // --- values
  ".a{color:#FF0000;background:#FFFFFF}",
  ".a{color:red;fill:white}",
  ".a{margin:0.5px;padding:1.50px;top:+2px}",
  ".a{background:url('a b.png')}",
  ".a{background:url(\"a.png\")}",
  ".a{content:\"\\2014\"}",
  ".a{transition:all .3s ease-in-out}",
  ".a{grid-template-areas:\"a b\" \"c d\"}",
  ".a{--custom-Prop:Red;color:var(--custom-Prop)}",
  ".a{filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#FF000000')}",
  ".a{width:calc(100% - 10px)}",
  ".a{clip:rect(0,0,0,0)}.b{clip:rect(0 0 0 0)}",
  "*{margin:0}",
  ".a>.b+.c~.d e{color:red}",
  ".a[data-x=\"1\"]{color:red}",
  ".a[data-x=\"1\" i]{color:red}",
  ":root{--x:1}",
  ".a{color:RED}",
  "DIV{color:red}",
];
