export const cases2 = [
  // --- colors (csso replace/color.js)
  ".a{color:rgb(255,0,0)}",
  ".a{color:rgb(255 0 0)}",
  ".a{color:rgba(255,0,0,1)}",
  ".a{color:rgba(255,0,0,.5)}",
  ".a{color:hsl(0,100%,50%)}",
  ".a{color:hsla(0,100%,50%,1)}",
  ".a{color:#ff0000}",
  ".a{color:#FFFFFF}",
  ".a{color:#f00}",
  ".a{color:white}",
  ".a{color:black}",
  ".a{color:fuchsia}",
  ".a{color:cyan}",
  ".a{color:transparent}",
  ".a{border:1px solid rgb(0,0,0)}",
  ".a{color:rgb(300,0,0)}",
  ".a{color:rgba(0,0,0,0)}",
  // --- dimensions / numbers (csso replace/Dimension.js, Number.js, Percentage.js)
  ".a{width:0px}",
  ".a{width:0%}",
  ".a{margin:0px 0em 0pt 0in}",
  ".a{width:010.50px}",
  ".a{width:+1px}",
  ".a{line-height:1.0}",
  ".a{width:1e3px}",
  ".a{transition-duration:0s}",
  ".a{width:0.000px}",
  ".a{z-index:0001}",
  // --- font shorthand (csso replace/property/font.js)
  ".a{font:normal normal 12px/1.2 Arial}",
  ".a{font:bold 12px Arial}",
  ".a{font-weight:normal}",
  ".a{font-weight:bold}",
  ".a{font-weight:400}",
  ".a{font-weight:700}",
  ".a{font:12px Arial,sans-serif}",
  // --- background shorthand (csso replace/property/background.js)
  ".a{background:none repeat scroll 0 0 red}",
  ".a{background:transparent none}",
  ".a{background:url(a.png) 0 0 no-repeat}",
  // --- border/outline (csso replace/property/border.js)
  ".a{border:medium none}",
  ".a{outline:medium none}",
  ".a{border:none}",
  ".a{border:1px none red}",
  // --- at-rules
  "@media (min-width:100px) and (max-width:200px){.a{color:red}}",
  "@media only screen and (-webkit-min-device-pixel-ratio:1.5){.a{color:red}}",
  "@media (min-resolution:2dppx){.a{color:red}}",
  "@supports not (display:grid){.a{float:left}}",
  "@page :first{margin:1in}",
  "@font-face{font-family:'My Font';src:url(a.woff2) format('woff2')}",
  "@namespace svg url(http://www.w3.org/2000/svg);",
  "@layer base{.a{color:red}}",
  "@container (min-width:200px){.a{color:red}}",
  "@keyframes a{0%{opacity:0}50%{opacity:.5}100%{opacity:1}}",
  "@keyframes a{from{opacity:0}to{opacity:1}}",
  "@media screen{.a{color:red}.a{color:blue}}",
  // --- selectors
  ".a[data-x=abc]{color:red}",
  ".a[data-x=\"abc\"]{color:red}",
  ".a[data-x=\"a b\"]{color:red}",
  ".a[data-x=\"1abc\"]{color:red}",
  ".a[data-x=\"-abc\"]{color:red}",
  ".a[data-x=\"--abc\"]{color:red}",
  ".a[ data-x ]{color:red}",
  "a:not(.b .c){color:red}",
  "a:is(.b,.c){color:red}",
  "a:where(.b){color:red}",
  "a:nth-child( 2n + 1 ){color:red}",
  "a::first-line{color:red}",
  "a:first-line{color:red}",
  "* html .a{color:red}",
  "svg|rect{fill:red}",
  ".a   .b   >   .c{color:red}",
  "a\\:b{color:red}",
  "#\\31 23{color:red}",
  // --- svg-ish
  ".cls-1{fill:#fff;stroke:#000;stroke-width:2px}",
  ".st0{fill:none;stroke:#231f20;stroke-miterlimit:10}",
  "path{fill:red}circle{fill:red}rect{fill:red}",
  ".a{stroke-dasharray:1,2,3}",
  ".a{transform:translate(1px,2px) rotate(45deg)}",
  ".a{marker-end:url(#arrow)}",
  "text{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif}",
  // --- edge cases
  ".a{color:red;;}",
  ".a{;color:red}",
  ".a{color:}",
  ".a{:red}",
  "@media{}",
  "}{",
  ".a{color:red}}",
  ".a{width:calc(100%/3)}",
  ".a{width:calc((100% - 10px)/3)}",
  ".a{background-image:linear-gradient(to right,red 0,blue 100%)}",
  ".a{grid-template-columns:repeat(auto-fill,minmax(100px,1fr))}",
  ".a{--x:{a:b}}",
  ".a{color:red!IMPORTANT}",
  ".a{color:red ! important}",
  ".a{COLOR:red}",
  ".A{color:red}",
  "DIV P{color:red}",
  ".a{box-shadow:0 0 1px white}",
  ".a{text-shadow:1px 1px 2px black}",
  ".a{background-image:linear-gradient(to right,white,black)}",
  ".a{background-image:radial-gradient(rgba(0,0,0,0),blue)}",
  ".a{background-image:linear-gradient(red,rgba(255,0,0,0))}",
  ".a{background:-webkit-linear-gradient(top,white,black)}",
  ".a{color:rgb(255,0,0,.5)}",
  ".a{color:hsl(120,100%,25%)}",
  ".a{stop-color:white}",
  ".a{flood-color:white}",
  ".a{font-family:tan}",
  ".a{animation:1s tan}",
  ".a{width:calc(0px + 1px)}",
  ".a{margin:calc(1px)}",
  ".a{background-position:0%}",
  ".a{font-size:0%}",
  ".a{border-width:0px}",
  ".a{stroke-width:0px}",
  ".a{stroke-dasharray:0px 1px}",
  ".a{flex:0px}",
  ".a{flex-basis:0px}",
  ".a{font:normal}",
  ".a{font:normal normal normal 12px Arial}",
  ".a{background:red none repeat}",
  ".a{background:url(a.png),url(b.png)}",
  ".a{border:0}",
  ".a{outline:none}",
  ".a{font-weight:bolder}",
  ".a{transform:translate(0%,0%)}",
  ".a{transform:translateX(0%)}",
  ".a{transform:scale(0%)}",
  ".a{transform:matrix(1,0,0,1,0%,0%)}",
  ".a{clip-path:inset(0%)}",
  ".a{clip-path:polygon(0% 0%,1px 1px)}",
  ".a{filter:blur(0%)}",
  ".a{grid-template-columns:minmax(0%,1fr)}",
  ".a{width:fit-content(0%)}",
  ".a{width:calc(0%)}",
  ".a{margin:calc(0%)}",
  ".a{scrollbar-color:white black}",
  ".a{scrollbar-color:white}",
  ".a{box-shadow:1px white}",
  ".a{box-shadow:1px 1px white}",
  ".a{box-shadow:inset 1px 1px white}",
  ".a{text-shadow:1px white}",
  ".a{stop-color:white}",
  ".a{lighting-color:white}",
  ".a{stroke-width:0%}",
  ".a{stroke-dasharray:0% 1px}",
  ".a{background-position:0% 50%}",
  ".a{my-unknown-prop:0%}",
  ".a{my-unknown-prop:white}",
  ".a{translate:0%}",
  ".a{rotate:0%}",
  ".a{padding:0%}",
  ".a{margin:0% 10px}",
  ".a{top:0%}",
  ".a{left:0%}",
  ".a{height:0%}",
  ".a{line-height:0%}",
  ".a{flex-basis:0%}",
  ".a{flex:0%}",
  ".a{stroke-dasharray:0%}",
  ".a{stroke-dashoffset:0%}",
  ".a{grid-template-columns:0%}",
  ".a{background:0% 0% red}",
  ".a{border-radius:0%}",
  ".a{-x-foo:0%}",
  ".a{--custom:0%}",
  ".a{opacity:0%}",
  ".a{border-width:0%}",
  ".a{opacity:0px}",
  ".a{my-unknown-prop:0px}",
  ".a{line-height:0px}",
  ".a{fill:white}",
  ".a{stroke:white}",
  ".a{box-shadow:white}",
  ".a{text-shadow:0 0 1px white}",
  ".a{-webkit-box-shadow:0 0 1px white}",
  ".a{font:12px white}",
  ".a{-x-foo:white}",
  ".a{--custom:white}",
  ".a{border:1px solid white}",
  ".a{outline:1px solid white}",
  ".a{caret-color:white}",
  ".a{column-rule:1px solid white}",
  ".a{text-decoration-color:white}",
  ".a{background-image:linear-gradient(white,black)}",
  ".a{stroke:linear-gradient(white,black)}",
  ".a{background:url(a.png) white}",
  ".a{list-style:none white}",
];
